from general_tests import *
from profile_tests import *
from ratings_tests import *
from search_tests import *
from basket_tests import *
from short_review_tests import *
from post_tests import *
from comment_tests import *
from messages_tests import *
from followers_tests import *
from showtimes_tests import *
from festival_tests import *
