from django.conf.urls.defaults import *
from handlers import *
handler404 = 'film20.api.views.handler404'

userpatterns = patterns('',
    url('^$', user_handler),
    url('^recommendations/$', user_recommendations_handler),
    url('^films-unrated/$', user_unrated_films_handler),
    url('^ratings/film/$', film_ratings_handler),
    url('^ratings/film/(?P<permalink>[^/]+)/$', film_ratings_handler),
    url('^ratings/film/(?P<permalink>[^/]+)/(?P<type>\d+)/$', film_rating_handler),
    url('^meta/film/(?P<permalink>[^/]+)/$', user_film_meta_handler),
    url('^short-reviews/$', user_short_reviews_handler),
    url('^short-reviews/(?P<permalink>[^/]+)/$', user_short_review_handler),
    url('^short-reviews/(?P<permalink>[^/]+)/comments/$', user_short_review_comments_handler),
    url('^filmbasket/$', user_basket_handler, name='user_basket_handler'),
    url('^filmbasket/(?P<permalink>[^/]+)/$', user_basketitem_handler, name='user_basketitem_handler'),

    url('^shitlist/$', user_basket_handler, {'type': 'SHITLIST'}, 
                                                name='user_shitlist_handler'),
    url('^shitlist/(?P<permalink>[^/]+)/$', user_basketitem_handler, {'type': 'SHITLIST'}, 
                                                name='user_shitlistitem_handler'),
    url('^wishlist/$', user_basket_handler, {'type': 'WISHLIST'},
                                                name='user_wishlist_handler'),
    url('^wishlist/(?P<permalink>[^/]+)/$', user_basketitem_handler, {'type': 'WISHLIST'}, 
                                                name='user_wishlistitem_handler'),
    url('^films-owned/$', user_basket_handler, {'type': 'OWNED'},
                                                name='user_films_owned_handler'),
    url('^films-owned/(?P<permalink>[^/]+)/$', user_basketitem_handler, {'type': 'OWNED'}, 
                                                name='user_films_owned_item_handler'),
    
    url('^posts/(?P<id>\d+)/$', user_post_handler),
    url('^posts/$', user_post_handler),
    url('^posts/(?P<id>\d+)/comments/$', user_post_comments_handler),
    url('^posts/(?P<id>\d+)/related-(?P<type>films|persons)/$', user_post_related_handler),
    url('^posts/(?P<id>\d+)/related-(?P<type>films|persons)/(?P<related_permalink>[^/]+)/$', user_post_related_handler),
    
    url('^activities/$', user_activity_handler),
    url('^activities/(?P<filter>short_reviews|posts|comments|links|follows)/$', user_activity_handler),
    url('^activities/(?P<id>\d+)/$', user_activity_handler),
    
    url('^showtimes/$', user_showtimes_handler),
    url('^showtimes/(?P<date>\d\d\d\d-\d\d-\d\d)/$', user_showtimes_handler),
    
    url('^channel/$', old_user_channel_handler),
    url('^channel/showtimes/$', user_channel_showtimes_handler),
    url('^channel/showtimes/(?P<date>\d\d\d\d-\d\d-\d\d)/$', user_channel_showtimes_handler),

    url('^channels/$', user_channel_handler),
    url('^channels/(?P<id>\d+)/$', user_channel_handler),
    
    #followers
    url('^following/$', user_following_handler),
    url('^following/(?P<peername>[^/]+)/$', user_following_handler),
    url('^followers/$', user_followers_handler),
    url('^followers/(?P<peername>[^/]+)/$', user_followers_handler),
    url('^blocking/$', user_blocking_handler),
    url('^blocking/(?P<peername>[^/]+)/$', user_blocking_handler),
    url('^blockers/$', user_blockers_handler),
    url('^blockers/(?P<peername>[^/]+)/$', user_blockers_handler),
    url('^friends/$', user_friends_handler),
    url('^friends/(?P<peername>[^/]+)/$', user_friends_handler),
    
    url('^community/$', user_community_handler),
    url('^checkin/$', user_checkin_handler),

)

urlpatterns = patterns('',
    url('^profile/', include(userpatterns)),
    url('^profile/messages/$', message_handler),
    url('^profile/conversations/(?P<id>\d+)/$', conversation_handler),
    url('^profile/conversations/$', conversation_handler),
    url('^profile/conversations/(?P<id>\d+)/messages/$', conversation_messages_handler),
    url('^profile/messages/(?P<filter>inbox|outbox|trash)/$', message_handler),
    url('^profile/messages/(?P<id>\d+)/$', message_handler),

    url('^user/(?P<username>[^/]+)/',include(userpatterns)),

    url('^planet/$', planet_handler),
    url('^comment/$', comment_handler),
    url('^comment/(?P<id>\d+)/$', comment_handler),
    url('^film/(?P<permalink>[^/]+)/links/$', film_links_handler),
    url('^film/(?P<permalink>[^/]+)/links/(?P<type>\d+|video)/$', film_links_handler),
    url('^film/(?P<permalink>[^/]+)/characters/$', film_characters_handler),
    url('^film/(?P<permalink>[^/]+)/related/$', film_related_handler),
    url('^film/(?P<permalink>[^/]+)/short-reviews/$', film_short_reviews_handler),
    url('^film/(?P<permalink>[^/]+)/posts/$', film_posts_handler),
    url('^film/(?P<permalink>[^/]+)/$', film_handler),
    url('^film/(?P<permalink>[^/]+)/activities/reviews/$', film_activity_handler),
    url('^film/(?P<permalink>[^/]+)/checkin/$', film_checkin_handler),
    url('^film/(?P<permalink>[^/]+)/checkin/(?P<username>[^/]+)/$', film_checkin_handler),
    url('^person/(?P<permalink>[^/]+)/$', person_handler),
    url('^person/(?P<permalink>[^/]+)/films-played/$', films_played_handler),
    url('^person/(?P<permalink>[^/]+)/films-directed/$', films_directed_handler),
    url('^person/(?P<permalink>[^/]+)/posts/$', person_posts_handler),
    
    url('^search/film/$', search_film_handler),
    url('^search/person/$', search_person_handler),
    url('^search/user/$', search_user_handler),
    url('^search/$', search_handler),

    url('^search/town/$', search_town_handler),
    
    url('^country/$', country_handler),
    url('^country/(?P<id>\w\w|\d+)/$', country_handler),
    url('^country/(?P<code>\w\w)/tvchannel/$', country_tvchannel_handler),
    url('^country/(?P<code>\w\w)/festival/$', country_festival_handler),
    url('^country/(?P<code>\w\w)/festival/(?P<id>\d+)/$', country_festival_handler),
    url('^town/(?P<id>\w\w|\d+)/$', town_handler),
    url('^town/(?P<id>\w\w|\d+)/cinema/$', town_cinema_handler),
    url('^town/(?P<id>\w\w|\d+)/cinema/showtimes/$', town_cinema_showtimes_handler),
    url('^town/(?P<id>\w\w|\d+)/cinema/showtimes/(?P<date>\d\d\d\d-\d\d-\d\d)/$', town_cinema_showtimes_handler),
    url('^town/(?P<id>\w\w|\d+)/showtimes/$', town_showtimes_handler),
    url('^town/(?P<id>\w\w|\d+)/showtimes/(?P<date>\d\d\d\d-\d\d-\d\d)/$', town_showtimes_handler),
    url('^channel/(?P<id>\d+)/$', channel_handler),
    url('^channel/(?P<id>\d+)/showtimes/$', channel_showtimes_handler),
    url('^channel/(?P<id>\d+)/showtimes/(?P<date>\d\d\d\d-\d\d-\d\d)/$', channel_showtimes_handler),
    url('^screening/(?P<id>\d+)/$', screening_handler),
    url('^screening/(?P<id>\d+)/checkin/$', screening_checkin_handler),
    url('^screening/(?P<id>\d+)/checkin/(?P<username>[^/]+)/$', screening_checkin_handler),
    url('^checkin/(?P<id>\d+)/$', checkin_handler),
    url('^checkin/(?P<id>\d+)/comments/$', checkin_comments_handler),
    url('^checkin/$', checkin_handler),
    url('^link/(?P<id>\d+)/$', external_link_handler),
    url('^ranking/film/$', film_ranking_handler),
)
