UPDATE core_character SET character='On sam' WHERE "LANG"='pl' AND character='Himself';
UPDATE core_character SET character='Tancerz' WHERE "LANG"='pl' AND character='Dancer';
UPDATE core_character SET character='Statysta' WHERE "LANG"='pl' AND character='Extra';
UPDATE core_character SET character='Ona sama' WHERE "LANG"='pl' AND character='Herself';
UPDATE core_character SET character='Dodatkowe głosy' WHERE "LANG"='pl' AND character='Additional Voices';
UPDATE core_character SET character='Pielęgniarka' WHERE "LANG"='pl' AND character='Nurse';
UPDATE core_character SET character='Policjant' WHERE "LANG"='pl' AND character='Policeman';
UPDATE core_character SET character='Doktor' WHERE "LANG"='pl' AND character='Doctor';
UPDATE core_character SET character='Barman' WHERE "LANG"='pl' AND character='Bartender';
UPDATE core_character SET character='Kelner' WHERE "LANG"='pl' AND character='Waiter';
UPDATE core_character SET character='Gość' WHERE "LANG"='pl' AND character='Party Guest';
UPDATE core_character SET character='Kelnerka' WHERE "LANG"='pl' AND character='Waitress';
UPDATE core_character SET character='Żołnież' WHERE "LANG"='pl' AND character='Soldier';
UPDATE core_character SET character='Ksiądz' WHERE "LANG"='pl' AND character='Priest';
UPDATE core_character SET character='Policjant' WHERE "LANG"='pl' AND character='Cop';
UPDATE core_character SET character='Ochroniarz' WHERE "LANG"='pl' AND character='Guard';
UPDATE core_character SET character='Dodatkowy głos' WHERE "LANG"='pl' AND character='Additional Voice';
UPDATE core_character SET character='Detektyw' WHERE "LANG"='pl' AND character='Detective';
UPDATE core_character SET character='Ochroniarz' WHERE "LANG"='pl' AND character='Security Guard';
UPDATE core_character SET character='Dziewczyna' WHERE "LANG"='pl' AND character='Girl';
UPDATE core_character SET character='Mężczyzna' WHERE "LANG"='pl' AND character='Man';
UPDATE core_character SET character='Oficer Policji' WHERE "LANG"='pl' AND character='Police Officer';
UPDATE core_character SET character='Fotograf' WHERE "LANG"='pl' AND character='Photographer';
UPDATE core_character SET character='Kobieta' WHERE "LANG"='pl' AND character='Woman';
UPDATE core_character SET character='Sędzia' WHERE "LANG"='pl' AND character='Judge';
UPDATE core_character SET character='Nauczyciel' WHERE "LANG"='pl' AND character='Teacher';
UPDATE core_character SET character='Recepcjonista' WHERE "LANG"='pl' AND character='Receptionist';
UPDATE core_character SET character='Matka' WHERE "LANG"='pl' AND character='Mother';
UPDATE core_character SET character='Sekretarka' WHERE "LANG"='pl' AND character='Secretary';
UPDATE core_character SET character='Prezenter' WHERE "LANG"='pl' AND character='Newscaster';
UPDATE core_character SET character='Wokalista' WHERE "LANG"='pl' AND character='Singer';
UPDATE core_character SET character='Chłopiec' WHERE "LANG"='pl' AND character='Boy';
UPDATE core_character SET character='Taksówkarz' WHERE "LANG"='pl' AND character='Taxi Driver';
UPDATE core_character SET character='Więzień' WHERE "LANG"='pl' AND character='Prisoner';
UPDATE core_character SET character='Oficer' WHERE "LANG"='pl' AND character='Officer';
UPDATE core_character SET character='Patron baru' WHERE "LANG"='pl' AND character='Bar Patron';
UPDATE core_character SET character='Kierowca' WHERE "LANG"='pl' AND character='Driver';
UPDATE core_character SET character='Agent FBI' WHERE "LANG"='pl' AND character='FBI Agent';
UPDATE core_character SET character='Gość weselny' WHERE "LANG"='pl' AND character='Wedding Guest';
UPDATE core_character SET character='Pilot helikoptera' WHERE "LANG"='pl' AND character='Helicopter Pilot';
UPDATE core_character SET character='Muzyk' WHERE "LANG"='pl' AND character='Musician';
UPDATE core_character SET character='Odludek' WHERE "LANG"='pl' AND character='Thug';
UPDATE core_character SET character='Uczeń' WHERE "LANG"='pl' AND character='School Kid';
UPDATE core_character SET character='Ratownik medyczny' WHERE "LANG"='pl' AND character='Paramedic';
UPDATE core_character SET character='Ochroniarz więzienny' WHERE "LANG"='pl' AND character='Prison Guard';
UPDATE core_character SET character='Starszy człowiek' WHERE "LANG"='pl' AND character='Old Man';
UPDATE core_character SET character='Model' WHERE "LANG"='pl' AND character='Model';
UPDATE core_character SET character='Prawnik' WHERE "LANG"='pl' AND character='Lawyer';
UPDATE core_character SET character='Pasażer ' WHERE "LANG"='pl' AND character='Passenger';

