# This is an auto-generated Django model module created by ogrinspect.
from django.db import models
from django.conf import settings

import logging
logger = logging.getLogger(__name__)

from .middleware import LazyGeo
from film20.core.models import Profile

models.signals.post_save.connect(LazyGeo.profile_post_save, sender=Profile)

class BaseTimeZone(models.Model):
    class Meta:
        abstract = True

    @classmethod
    def tzid_for_country(cls, code):
        timezones = cls.COUNTRY_TIMEZONES.get(code)
        return timezones and timezones[0] or None

    COUNTRY_TIMEZONES = {
         u'AD': [u'Europe/Andorra'],
         u'AE': [u'Asia/Dubai'],
         u'AF': [u'Asia/Kabul'],
         u'AG': [u'America/Antigua'],
         u'AI': [u'America/Anguilla'],
         u'AL': [u'Europe/Tirane'],
         u'AM': [u'Asia/Yerevan'],
         u'AN': [u'America/Curacao'],
         u'AO': [u'Africa/Luanda'],
         u'AQ': [u'Antarctica/McMurdo',
          u'Antarctica/South_Pole',
          u'Antarctica/Rothera',
          u'Antarctica/Palmer',
          u'Antarctica/Mawson',
          u'Antarctica/Davis',
          u'Antarctica/Casey',
          u'Antarctica/Vostok',
          u'Antarctica/DumontDUrville',
          u'Antarctica/Syowa',
          u'Antarctica/Macquarie'],
         u'AR': [u'America/Argentina/Buenos_Aires',
          u'America/Argentina/Cordoba',
          u'America/Argentina/Salta',
          u'America/Argentina/Jujuy',
          u'America/Argentina/Tucuman',
          u'America/Argentina/Catamarca',
          u'America/Argentina/La_Rioja',
          u'America/Argentina/San_Juan',
          u'America/Argentina/Mendoza',
          u'America/Argentina/San_Luis',
          u'America/Argentina/Rio_Gallegos',
          u'America/Argentina/Ushuaia'],
         u'AS': [u'Pacific/Pago_Pago'],
         u'AT': [u'Europe/Vienna'],
         u'AU': [u'Australia/Sydney',
          u'Australia/Melbourne',
          u'Australia/Lord_Howe',
          u'Australia/Hobart',
          u'Australia/Currie',
          u'Australia/Broken_Hill',
          u'Australia/Brisbane',
          u'Australia/Lindeman',
          u'Australia/Adelaide',
          u'Australia/Darwin',
          u'Australia/Perth',
          u'Australia/Eucla'],
         u'AW': [u'America/Aruba'],
         u'AX': [u'Europe/Mariehamn'],
         u'AZ': [u'Asia/Baku'],
         u'BA': [u'Europe/Sarajevo'],
         u'BB': [u'America/Barbados'],
         u'BD': [u'Asia/Dhaka'],
         u'BE': [u'Europe/Brussels'],
         u'BF': [u'Africa/Ouagadougou'],
         u'BG': [u'Europe/Sofia'],
         u'BH': [u'Asia/Bahrain'],
         u'BI': [u'Africa/Bujumbura'],
         u'BJ': [u'Africa/Porto-Novo'],
         u'BL': [u'America/St_Barthelemy'],
         u'BM': [u'Atlantic/Bermuda'],
         u'BN': [u'Asia/Brunei'],
         u'BO': [u'America/La_Paz'],
         u'BR': [u'America/Noronha',
          u'America/Belem',
          u'America/Fortaleza',
          u'America/Recife',
          u'America/Araguaina',
          u'America/Maceio',
          u'America/Bahia',
          u'America/Sao_Paulo',
          u'America/Campo_Grande',
          u'America/Cuiaba',
          u'America/Santarem',
          u'America/Porto_Velho',
          u'America/Boa_Vista',
          u'America/Manaus',
          u'America/Eirunepe',
          u'America/Rio_Branco'],
         u'BS': [u'America/Nassau'],
         u'BT': [u'Asia/Thimphu'],
         u'BW': [u'Africa/Gaborone'],
         u'BY': [u'Europe/Minsk'],
         u'BZ': [u'America/Belize'],
         u'CA': [u'America/St_Johns',
          u'America/Halifax',
          u'America/Glace_Bay',
          u'America/Moncton',
          u'America/Goose_Bay',
          u'America/Blanc-Sablon',
          u'America/Montreal',
          u'America/Toronto',
          u'America/Nipigon',
          u'America/Thunder_Bay',
          u'America/Iqaluit',
          u'America/Pangnirtung',
          u'America/Resolute',
          u'America/Atikokan',
          u'America/Rankin_Inlet',
          u'America/Winnipeg',
          u'America/Rainy_River',
          u'America/Regina',
          u'America/Swift_Current',
          u'America/Edmonton',
          u'America/Cambridge_Bay',
          u'America/Yellowknife',
          u'America/Inuvik',
          u'America/Dawson_Creek',
          u'America/Vancouver',
          u'America/Whitehorse',
          u'America/Dawson'],
         u'CC': [u'Indian/Cocos'],
         u'CD': [u'Africa/Kinshasa', u'Africa/Lubumbashi'],
         u'CF': [u'Africa/Bangui'],
         u'CG': [u'Africa/Brazzaville'],
         u'CH': [u'Europe/Zurich'],
         u'CI': [u'Africa/Abidjan'],
         u'CK': [u'Pacific/Rarotonga'],
         u'CL': [u'America/Santiago', u'Pacific/Easter'],
         u'CM': [u'Africa/Douala'],
         u'CN': [u'Asia/Shanghai',
          u'Asia/Harbin',
          u'Asia/Chongqing',
          u'Asia/Urumqi',
          u'Asia/Kashgar'],
         u'CO': [u'America/Bogota'],
         u'CR': [u'America/Costa_Rica'],
         u'CU': [u'America/Havana'],
         u'CV': [u'Atlantic/Cape_Verde'],
         u'CX': [u'Indian/Christmas'],
         u'CY': [u'Asia/Nicosia'],
         u'CZ': [u'Europe/Prague'],
         u'DE': [u'Europe/Berlin'],
         u'DJ': [u'Africa/Djibouti'],
         u'DK': [u'Europe/Copenhagen'],
         u'DM': [u'America/Dominica'],
         u'DO': [u'America/Santo_Domingo'],
         u'DZ': [u'Africa/Algiers'],
         u'EC': [u'America/Guayaquil', u'Pacific/Galapagos'],
         u'EE': [u'Europe/Tallinn'],
         u'EG': [u'Africa/Cairo'],
         u'EH': [u'Africa/El_Aaiun'],
         u'ER': [u'Africa/Asmara'],
         u'ES': [u'Europe/Madrid', u'Africa/Ceuta', u'Atlantic/Canary'],
         u'ET': [u'Africa/Addis_Ababa'],
         u'FI': [u'Europe/Helsinki'],
         u'FJ': [u'Pacific/Fiji'],
         u'FK': [u'Atlantic/Stanley'],
         u'FM': [u'Pacific/Chuuk', u'Pacific/Pohnpei', u'Pacific/Kosrae'],
         u'FO': [u'Atlantic/Faroe'],
         u'FR': [u'Europe/Paris'],
         u'GA': [u'Africa/Libreville'],
         u'GB': [u'Europe/London'],
         u'GD': [u'America/Grenada'],
         u'GE': [u'Asia/Tbilisi'],
         u'GF': [u'America/Cayenne'],
         u'GG': [u'Europe/Guernsey'],
         u'GH': [u'Africa/Accra'],
         u'GI': [u'Europe/Gibraltar'],
         u'GL': [u'America/Godthab',
          u'America/Danmarkshavn',
          u'America/Scoresbysund',
          u'America/Thule'],
         u'GM': [u'Africa/Banjul'],
         u'GN': [u'Africa/Conakry'],
         u'GP': [u'America/Guadeloupe'],
         u'GQ': [u'Africa/Malabo'],
         u'GR': [u'Europe/Athens'],
         u'GS': [u'Atlantic/South_Georgia'],
         u'GT': [u'America/Guatemala'],
         u'GU': [u'Pacific/Guam'],
         u'GW': [u'Africa/Bissau'],
         u'GY': [u'America/Guyana'],
         u'HK': [u'Asia/Hong_Kong'],
         u'HN': [u'America/Tegucigalpa'],
         u'HR': [u'Europe/Zagreb'],
         u'HT': [u'America/Port-au-Prince'],
         u'HU': [u'Europe/Budapest'],
         u'ID': [u'Asia/Jakarta',
          u'Asia/Pontianak',
          u'Asia/Makassar',
          u'Asia/Jayapura'],
         u'IE': [u'Europe/Dublin'],
         u'IL': [u'Asia/Jerusalem'],
         u'IM': [u'Europe/Isle_of_Man'],
         u'IN': [u'Asia/Kolkata'],
         u'IO': [u'Indian/Chagos'],
         u'IQ': [u'Asia/Baghdad'],
         u'IR': [u'Asia/Tehran'],
         u'IS': [u'Atlantic/Reykjavik'],
         u'IT': [u'Europe/Rome'],
         u'JE': [u'Europe/Jersey'],
         u'JM': [u'America/Jamaica'],
         u'JO': [u'Asia/Amman'],
         u'JP': [u'Asia/Tokyo'],
         u'KE': [u'Africa/Nairobi'],
         u'KG': [u'Asia/Bishkek'],
         u'KH': [u'Asia/Phnom_Penh'],
         u'KI': [u'Pacific/Tarawa', u'Pacific/Enderbury', u'Pacific/Kiritimati'],
         u'KM': [u'Indian/Comoro'],
         u'KN': [u'America/St_Kitts'],
         u'KP': [u'Asia/Pyongyang'],
         u'KR': [u'Asia/Seoul'],
         u'KW': [u'Asia/Kuwait'],
         u'KY': [u'America/Cayman'],
         u'KZ': [u'Asia/Almaty',
          u'Asia/Qyzylorda',
          u'Asia/Aqtobe',
          u'Asia/Aqtau',
          u'Asia/Oral'],
         u'LA': [u'Asia/Vientiane'],
         u'LB': [u'Asia/Beirut'],
         u'LC': [u'America/St_Lucia'],
         u'LI': [u'Europe/Vaduz'],
         u'LK': [u'Asia/Colombo'],
         u'LR': [u'Africa/Monrovia'],
         u'LS': [u'Africa/Maseru'],
         u'LT': [u'Europe/Vilnius'],
         u'LU': [u'Europe/Luxembourg'],
         u'LV': [u'Europe/Riga'],
         u'LY': [u'Africa/Tripoli'],
         u'MA': [u'Africa/Casablanca'],
         u'MC': [u'Europe/Monaco'],
         u'MD': [u'Europe/Chisinau'],
         u'ME': [u'Europe/Podgorica'],
         u'MF': [u'America/Marigot'],
         u'MG': [u'Indian/Antananarivo'],
         u'MH': [u'Pacific/Majuro', u'Pacific/Kwajalein'],
         u'MK': [u'Europe/Skopje'],
         u'ML': [u'Africa/Bamako'],
         u'MM': [u'Asia/Rangoon'],
         u'MN': [u'Asia/Ulaanbaatar', u'Asia/Hovd', u'Asia/Choibalsan'],
         u'MO': [u'Asia/Macau'],
         u'MP': [u'Pacific/Saipan'],
         u'MQ': [u'America/Martinique'],
         u'MR': [u'Africa/Nouakchott'],
         u'MS': [u'America/Montserrat'],
         u'MT': [u'Europe/Malta'],
         u'MU': [u'Indian/Mauritius'],
         u'MV': [u'Indian/Maldives'],
         u'MW': [u'Africa/Blantyre'],
         u'MX': [u'America/Mexico_City',
          u'America/Cancun',
          u'America/Merida',
          u'America/Monterrey',
          u'America/Matamoros',
          u'America/Mazatlan',
          u'America/Chihuahua',
          u'America/Ojinaga',
          u'America/Hermosillo',
          u'America/Tijuana',
          u'America/Santa_Isabel',
          u'America/Bahia_Banderas'],
         u'MY': [u'Asia/Kuala_Lumpur', u'Asia/Kuching'],
         u'MZ': [u'Africa/Maputo'],
         u'NA': [u'Africa/Windhoek'],
         u'NC': [u'Pacific/Noumea'],
         u'NE': [u'Africa/Niamey'],
         u'NF': [u'Pacific/Norfolk'],
         u'NG': [u'Africa/Lagos'],
         u'NI': [u'America/Managua'],
         u'NL': [u'Europe/Amsterdam'],
         u'NO': [u'Europe/Oslo'],
         u'NP': [u'Asia/Kathmandu'],
         u'NR': [u'Pacific/Nauru'],
         u'NU': [u'Pacific/Niue'],
         u'NZ': [u'Pacific/Auckland', u'Pacific/Chatham'],
         u'OM': [u'Asia/Muscat'],
         u'PA': [u'America/Panama'],
         u'PE': [u'America/Lima'],
         u'PF': [u'Pacific/Tahiti', u'Pacific/Marquesas', u'Pacific/Gambier'],
         u'PG': [u'Pacific/Port_Moresby'],
         u'PH': [u'Asia/Manila'],
         u'PK': [u'Asia/Karachi'],
         u'PL': [u'Europe/Warsaw'],
         u'PM': [u'America/Miquelon'],
         u'PN': [u'Pacific/Pitcairn'],
         u'PR': [u'America/Puerto_Rico'],
         u'PS': [u'Asia/Gaza'],
         u'PT': [u'Europe/Lisbon', u'Atlantic/Madeira', u'Atlantic/Azores'],
         u'PW': [u'Pacific/Palau'],
         u'PY': [u'America/Asuncion'],
         u'QA': [u'Asia/Qatar'],
         u'RE': [u'Indian/Reunion'],
         u'RO': [u'Europe/Bucharest'],
         u'RS': [u'Europe/Belgrade'],
         u'RU': [u'Europe/Kaliningrad',
          u'Europe/Moscow',
          u'Europe/Volgograd',
          u'Europe/Samara',
          u'Asia/Yekaterinburg',
          u'Asia/Omsk',
          u'Asia/Novosibirsk',
          u'Asia/Novokuznetsk',
          u'Asia/Krasnoyarsk',
          u'Asia/Irkutsk',
          u'Asia/Yakutsk',
          u'Asia/Vladivostok',
          u'Asia/Sakhalin',
          u'Asia/Magadan',
          u'Asia/Kamchatka',
          u'Asia/Anadyr'],
         u'RW': [u'Africa/Kigali'],
         u'SA': [u'Asia/Riyadh'],
         u'SB': [u'Pacific/Guadalcanal'],
         u'SC': [u'Indian/Mahe'],
         u'SD': [u'Africa/Khartoum'],
         u'SE': [u'Europe/Stockholm'],
         u'SG': [u'Asia/Singapore'],
         u'SH': [u'Atlantic/St_Helena'],
         u'SI': [u'Europe/Ljubljana'],
         u'SJ': [u'Arctic/Longyearbyen'],
         u'SK': [u'Europe/Bratislava'],
         u'SL': [u'Africa/Freetown'],
         u'SM': [u'Europe/San_Marino'],
         u'SN': [u'Africa/Dakar'],
         u'SO': [u'Africa/Mogadishu'],
         u'SR': [u'America/Paramaribo'],
         u'ST': [u'Africa/Sao_Tome'],
         u'SV': [u'America/El_Salvador'],
         u'SY': [u'Asia/Damascus'],
         u'SZ': [u'Africa/Mbabane'],
         u'TC': [u'America/Grand_Turk'],
         u'TD': [u'Africa/Ndjamena'],
         u'TF': [u'Indian/Kerguelen'],
         u'TG': [u'Africa/Lome'],
         u'TH': [u'Asia/Bangkok'],
         u'TJ': [u'Asia/Dushanbe'],
         u'TK': [u'Pacific/Fakaofo'],
         u'TL': [u'Asia/Dili'],
         u'TM': [u'Asia/Ashgabat'],
         u'TN': [u'Africa/Tunis'],
         u'TO': [u'Pacific/Tongatapu'],
         u'TR': [u'Europe/Istanbul'],
         u'TT': [u'America/Port_of_Spain'],
         u'TV': [u'Pacific/Funafuti'],
         u'TW': [u'Asia/Taipei'],
         u'TZ': [u'Africa/Dar_es_Salaam'],
         u'UA': [u'Europe/Kiev',
          u'Europe/Uzhgorod',
          u'Europe/Zaporozhye',
          u'Europe/Simferopol'],
         u'UG': [u'Africa/Kampala'],
         u'UM': [u'Pacific/Johnston', u'Pacific/Midway', u'Pacific/Wake'],
         u'US': [u'America/New_York',
          u'America/Detroit',
          u'America/Kentucky/Louisville',
          u'America/Kentucky/Monticello',
          u'America/Indiana/Indianapolis',
          u'America/Indiana/Vincennes',
          u'America/Indiana/Winamac',
          u'America/Indiana/Marengo',
          u'America/Indiana/Petersburg',
          u'America/Indiana/Vevay',
          u'America/Chicago',
          u'America/Indiana/Tell_City',
          u'America/Indiana/Knox',
          u'America/Menominee',
          u'America/North_Dakota/Center',
          u'America/North_Dakota/New_Salem',
          u'America/Denver',
          u'America/Boise',
          u'America/Shiprock',
          u'America/Phoenix',
          u'America/Los_Angeles',
          u'America/Anchorage',
          u'America/Juneau',
          u'America/Yakutat',
          u'America/Nome',
          u'America/Adak',
          u'Pacific/Honolulu'],
         u'UY': [u'America/Montevideo'],
         u'UZ': [u'Asia/Samarkand', u'Asia/Tashkent'],
         u'VA': [u'Europe/Vatican'],
         u'VC': [u'America/St_Vincent'],
         u'VE': [u'America/Caracas'],
         u'VG': [u'America/Tortola'],
         u'VI': [u'America/St_Thomas'],
         u'VN': [u'Asia/Ho_Chi_Minh'],
         u'VU': [u'Pacific/Efate'],
         u'WF': [u'Pacific/Wallis'],
         u'WS': [u'Pacific/Apia'],
         u'YE': [u'Asia/Aden'],
         u'YT': [u'Indian/Mayotte'],
         u'ZA': [u'Africa/Johannesburg'],
         u'ZM': [u'Africa/Lusaka'],
         u'ZW': [u'Africa/Harare'],
    }
    TIMEZONE_COUNTRY = {}

# create reverse tz -> country_code mapping
for country, timezones in BaseTimeZone.COUNTRY_TIMEZONES.items():
    for tz in timezones:
        BaseTimeZone.TIMEZONE_COUNTRY[tz] = country

if 'django.contrib.gis' in settings.INSTALLED_APPS:
    from django.contrib.gis.db import models as gismodels
    class TimeZone(BaseTimeZone):
        tzid = models.CharField(max_length=30)
        geom = gismodels.MultiPolygonField()
        objects = gismodels.GeoManager()

        def __unicode__(self):
            return self.tzid

        @property
        def country_code(self):
            return self.TIMEZONE_COUNTRY.get(self.tzid)

# Auto-generated `LayerMapping` dictionary for TimeZone model
timezone_mapping = {
    'tzid' : 'TZID',
    'geom' : 'MULTIPOLYGON',
}


